#!/bin/bash

# echo "$(date +'%a %d %b')  "
# echo "<span foreground=\"#D88568\"><b>$(date +'%a %d %b %T')</b></span>"

/home/glarsen/.config/i3blocks/scripts/dateandtime



if [ "$BLOCK_BUTTON" == "1" ]; then
		#--posx=$[$(xdotool getmouselocation | awk '{print $1}' | cut -d ':' -f2)-50] \
    i3-msg -q exec "LC_TIME=\"en_GB.UTF-8\" yad \
		--title "Calendar" \
		--sticky \
		--no-buttons \
		--posx="2280" \
		--posy=24 \
		--show-weeks \
		--calendar \
		--close-on-unfocus"
	return;
fi

if [ "$BLOCK_BUTTON" == "3" ]; then
   # nohup urxvt -title "STOPWATCH" -geometry 50x7 -e /usr/bin/urtimer -S -s &
   # sleep 0.1
   # xdotool getactivewindow windowmove x 24 &
   # return;
		#--posx=$[$(xdotool getmouselocation | awk '{print $1}' | cut -d ':' -f2)-50] \
    i3-msg -q exec "LC_TIME=\"en_GB.UTF-8\" yad \
		--title "Calendar" \
		--sticky \
		--no-buttons \
		--posx=2280 \
		--posy=24 \
		--show-weeks \
		--calendar"
	return;
fi
