#!/usr/bin/env bash

if [ "$BLOCK_BUTTON" == "1" ]; then
    notify-send "package updater" "updating packages"
    urxvt -title "PACMAN+AUR UPDATE" -e yaourt -Syua && echo Press any key to close && read &
    return;
fi


# Trigger the script thats doing the magic of not running an update as root, instead of "yaourt -Syya"
checkupdates &> /dev/null

CHECKUPDATES_DB="${TMPDIR:-/tmp}/checkup-db-${USER}/"
UPDATES=$(yaourt -Qua --dbpath ${CHECKUPDATES_DB} | wc -l)

[[ "${UPDATES}" = "0" ]] && exit 0

echo "   ${UPDATES} "
exit 33
