#!/bin/bash
#
# IRC highlight warn for weechat
# Add "/exec -bg <path>/irc_warn ${tg_date} ${tg_tag_nick}" in weechat
# beep trigger
#
# No parameters -> Reset highlight

FILE=$HOME/.weechat/highlight

if [ $# -eq 0 ]; then
   >$FILE
elif [ "$1" == "bar" ]; then
    if [ "$2" == "1" ]; then
        >$FILE
    fi
    count=$(cat $FILE | wc -l)
    last=$(tail -1 $FILE)
    if [ $count -gt 0 ]; then
        printf "[%s] %s\n" "$count" "$last"
    fi
else
    # Ignore seconds
    time="$(echo $2 | cut -d':' -f1-2)"
    # Cut large nicks > 8
    if [ "$(echo $3 | wc -m)" -gt 8 ]; then
      nick="$(echo $3 | cut -c 1-8)"
      nick=$nick"+"
    else
      nick="$(echo $3)"
    fi
    printf "%s %s\n" "${time}" "${nick}" >> $FILE
fi

exit
# Alert sound
if [ $# -gt 0 ]; then
  if [ -x "/usr/bin/aplay" ]; then
    /usr/bin/aplay -q $HOME/.config/sounds/chat.wav &
  fi
fi
