#!/bin/bash

URGENT_LOWER=-10
URGENT_HIGHER=25

ICON_SUNNY=""
ICON_CLOUDY=""
ICON_RAINY=""
ICON_STORM=""
ICON_SNOW=""
ICON_FOG=""

SYMBOL_CELSIUS="℃"

# Mappings https://api.met.no/weatherapi/weathericon/1.1/documentation

SYMBOL_SUNNY=("1")
# 1 Sun

SYMBOL_CLOUDY=("2" "3" "4")
# 2 LightCloud
# 3 PartlyCloud
# 4 Cloud

SYMBOL_RAINY=("5" "9" "10" "41" "40")
# 5 LightRainSun
# 9 LightRain
# 10 Rain
# 41 RainSun
# 40 DrizzleSun

SYMBOL_SNOW=("7" "12" "8" "13" "14" "49" "50" "47" "48" "42" "43" "44" "45" "46")
# 7 SleetSun
# 12 Sleet
# 8 SnowSun
# 13 Snow
# 14 SnowThunder
# 49 LightSnow
# 50 HeavySnow
# 47 LightSleet
# 48 HeavySleet
# 42 LightSleetSun
# 43 HeavySleetSun
# 44 LightSnowSun
# 45 HeavysnowSun
# 46 Drizzle

SYMBOL_FOG=("15")
# 15 Fog

SYMBOL_STORM=("6" "11" "20" "21" "22" "23" "24" "25" "26" "27" "28" "29" "30" "31" "32" "33" "34")
# 6 LightRainThunderSun
# 11 RainThunder
# 20 SleetSunThunder
# 21 SnowSunThunder
# 22 LightRainThunder
# 23 SleetThunder
# 24 DrizzleThunderSun
# 25 RainThunderSun
# 26 LightSleetThunderSun
# 27 HeavySleetThunderSun
# 28 LightSnowThunderSun
# 29 HeavySnowThunderSun
# 30 DrizzleThunder
# 31 LightSleetThunder
# 32 HeavySleetThunder
# 33 LightSnowThunder
# 34 HeavySnowThunder

TMP="$(mktemp)"
curl -s "https://api.met.no/weatherapi/locationforecast/2.0/classic?lat=59.925424&lon=10.929603" > ${TMP}
WEATHER_TEMP=$(xmllint --xpath '//weatherdata/product/time/location/temperature/@value' ${TMP} | head -1 | cut -d '"' -f2)
WEATHER_MAIN=$(xmllint --xpath '//weatherdata/product/time/location/symbol/@number' ${TMP} | head -1 | cut -d '"' -f2)
BORDER="  "

if [[ " ${SYMBOL_SNOW[@]} " =~ " ${WEATHER_MAIN} " ]]; then
  echo "${BORDER}${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}${BORDER}"
elif [[ " ${SYMBOL_RAINY[@]} " =~ " ${WEATHER_MAIN} " ]]; then
  echo "${BORDER}${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}${BORDER}"
elif [[ " ${SYMBOL_CLOUDY[@]} " =~ " ${WEATHER_MAIN} " ]]; then
  echo "${BORDER}${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}${BORDER}"
elif [[ " ${SYMBOL_SUNNY[@]} " =~ " ${WEATHER_MAIN} " ]]; then
  echo "${BORDER}${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}${BORDER}"
elif [[ " ${SYMBOL_FOG[@]} " =~ " ${WEATHER_MAIN} " ]]; then
  echo "${BORDER}${ICON_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}${BORDER}"
else
  echo "${BORDER}${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS}${BORDER}"
fi

if [[ "${WEATHER_TEMP%.*}" -lt "${URGENT_LOWER}" ]] || [[ "${WEATHER_TEMP%.*}" -gt "${URGENT_HIGHER}" ]]; then
  exit 33
fi
