#!/bin/bash

SCREEN_SIZE=$(/home/glarsen/.config/i3/scripts/active-monitor | sed 's/ /x/')
#SCREEN_SIZE=$(xrandr | awk '/*/ {print $1}' | head -1)

X_SIZE=780
Y_SIZE=50

X_POS=$[$(echo "${SCREEN_SIZE}" | cut -d 'x' -f1) / 2 - (${X_SIZE} / 2)]
Y_POS=$[$(echo "${SCREEN_SIZE}" | cut -d 'x' -f2) / 2 - (${Y_SIZE} / 2)]

if [ "${X_POS}" == "" ]; then
    X_POS=500
    Y_POS=460
fi

# Make sure we have needed variables
barText="${barText:-#eff1f5}"
barInActiveText="${barInActiveText:-#a7adba}"
barBackground="${barBackground:-#343d46}"
barFocusBackground="${barFocusBackground:-#65737e}"
barActiveBackground="${barActiveBackground:-#5f676a}"
barInActiveBackground="${barInActiveBackground:-#4f5b66}"
barSelectedBackground="${barSelectedBackground:-#343d46}"
barBorderActive="${barBorderActive:-#a3be8c}"

select=$(echo -e 'CANCEL\nREBOOT\nSHUTDOWN\nSUSPEND\nLOGOUT' | dmenu -nb "$barBackground" -nf "$barInActiveText" -sb "$barFocusBackground" -sf "$barText" -fn Tamsyn -h $Y_SIZE -w $X_SIZE -x $X_POS -y $Y_POS -i -p "What kind of exit: ")

case "$select" in
    CANCEL)
        exit 0;
        ;;
    REBOOT)
        reboot;
        ;;
    SHUTDOWN)
        ~/bin/shutdown.sh yes
        ;;
    SUSPEND)
        i3lock -f -l --nofork &
        systemctl suspend
        ;;
    LOGOUT)
        i3-msg exit;
        ;;
    *)
        exit 1
esac
