#!/bin/bash

SCREEN_SIZE=$(xrandr | awk '/*/ {print $1}' | head -1)

X_POS=$[$(echo "${SCREEN_SIZE}" | cut -d 'x' -f1) / 2 - 495]
Y_POS=$[$(echo "${SCREEN_SIZE}" | cut -d 'x' -f2) / 2 - 160]

if [ "${X_POS}" == "" ]; then
    X_POS=670
    Y_POS=500
fi


OPTION=""
declare -A ACTIONS

OLDIFS=$IFS; IFS=$'\n'; for config in $(/usr/bin/nmcli -f type,uuid,device,name -t connection \
    | awk -F ":" '/^vpn/ {print $2"|"$3"|"$4}'); do

    if [ "$OPTION" != "" ]; then OPTION="${OPTION}\n"; fi
    UUID=$(echo "$config" | cut -d '|' -f1)
    ACTIVE=$(echo "$config" | cut -d '|' -f2)
    NAME=$(echo "$config" | cut -d '|' -f3)

    if [ "$ACTIVE" != "" ]; then
        OPTION="DISCONNECT ($NAME)\n${OPTION}"
        ACTIONS["DISCONNECT ($NAME)"]="down $UUID"
    fi

    ACTIONS["$NAME"]="up $UUID"

    OPTION="${OPTION}${NAME}"
done
IFS=$OLDIFS

select=$(echo -e $OPTION | dmenu  -nb "#CED0D1" -nf "#3C3437" -fn Tamsyn-9 -h 40 -w 990 -x $X_POS -y $Y_POS -i -l 8 -p "VPN: ")

if [ "${ACTIONS[$select]}" != "" ]; then
    nmcli connection ${ACTIONS[$select]}
fi
